INCLUDEPATH += \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Engine \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Engine/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Engine/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Core \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/TraceLog/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Core/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/TraceLog \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CoreUObject \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/CoreUObject/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NetCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Net \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Net/Core/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Net/Core/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ApplicationCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/ApplicationCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/RHI \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/RHI/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Json \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Json/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SlateCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/SlateCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/InputCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/InputCore/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/InputCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Slate \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Slate/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ImageWrapper \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/ImageWrapper/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Messaging \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Messaging/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MessagingCommon \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/MessagingCommon/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/RenderCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/RenderCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AnalyticsET \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Analytics \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Analytics/AnalyticsET/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Analytics \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Analytics/Analytics/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Sockets \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Sockets/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NetCommon \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Net/Common/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AssetRegistry \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AssetRegistry/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EngineMessages \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/EngineMessages/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EngineSettings \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/EngineSettings/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/EngineSettings/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SynthBenchmark \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/SynthBenchmark/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Renderer \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Renderer/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GameplayTags \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/GameplayTags/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/GameplayTags/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/DeveloperSettings \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/DeveloperSettings/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PacketHandler \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PacketHandlers \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PacketHandlers/PacketHandler/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PacketHandlers/PacketHandler/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ReliabilityHandlerComponent \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PacketHandlers/ReliabilityHandlerComponent/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioPlatformConfiguration \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AudioPlatformConfiguration/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshDescription \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/MeshDescription/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/StaticMeshDescription \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/StaticMeshDescription/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PakFile \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PakFile/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/RSA \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/RSA/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NetworkReplayStreaming \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/NetworkReplayStreaming \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/NetworkReplayStreaming/NetworkReplayStreaming/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PhysicsCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PhysicsCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Chaos \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Experimental \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Experimental/Chaos/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ChaosCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Experimental/ChaosCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/Intel \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Voronoi \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Experimental/Voronoi/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SignalProcessing \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/SignalProcessing/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioExtensions \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AudioExtensions/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioMixerCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AudioMixerCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PropertyAccess \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PropertyAccess/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealEd \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Programs/UnrealLightmass/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/Android/AndroidDeviceDetection/Public/Interfaces \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/UnrealEd/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/UnrealEd/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/DirectoryWatcher \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/DirectoryWatcher/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Documentation \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/Documentation/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Projects \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Projects/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SandboxFile \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/SandboxFile/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EditorStyle \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/EditorStyle/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SourceControl \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/SourceControl/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealEdMessages \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/UnrealEdMessages/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/UnrealEdMessages/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GameplayDebugger \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/GameplayDebugger/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/BlueprintGraph \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/BlueprintGraph/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/BlueprintGraph/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/EditorSubsystem \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/EditorSubsystem/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HTTP \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Online \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Online/HTTP/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UnrealAudio \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/UnrealAudio/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/FunctionalTesting \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/FunctionalTesting/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/FunctionalTesting/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AutomationController \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/AutomationController/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Localization \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/Localization/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/AudioEditor/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/AudioEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AudioMixer \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AudioMixer/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AudioMixer/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/TargetPlatform \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/TargetPlatform/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/LevelEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/LevelEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Settings \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/Settings/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/IntroTutorials \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/IntroTutorials/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HeadMountedDisplay \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/HeadMountedDisplay/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/VREditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/VREditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/VREditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CommonMenuExtensions \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/CommonMenuExtensions/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Landscape \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Landscape/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Landscape/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PropertyEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/PropertyEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ActorPickerMode \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/ActorPickerMode/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SceneDepthPickerMode \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/SceneDepthPickerMode/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/DetailCustomizations \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/DetailCustomizations/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ClassViewer \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/ClassViewer/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GraphEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/GraphEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/StructViewer \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/StructViewer/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ContentBrowser \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/ContentBrowser/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ContentBrowserData \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/ContentBrowserData/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CollectionManager \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/CollectionManager/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NetworkFileSystem \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/NetworkFileSystem/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UMG \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/UMG/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MovieScene \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/MovieScene/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/TimeManagement \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/TimeManagement/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MovieSceneTracks \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/MovieSceneTracks/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AnimationCore \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AnimationCore/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/PropertyPath \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/PropertyPath/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/NavigationSystem \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/NavigationSystem/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshBuilder \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/MeshBuilder/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MaterialShaderQualitySettings \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/MaterialShaderQualitySettings/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/InteractiveToolsFramework \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/Experimental/InteractiveToolsFramework/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ToolMenusEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/ToolMenusEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ToolMenus \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/ToolMenus/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AssetTagsEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/AssetTagsEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AddContentDialog \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/AddContentDialog/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshUtilities \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/MeshUtilities/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshMergeUtilities \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/MeshMergeUtilities/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/HierarchicalLODUtilities \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/HierarchicalLODUtilities/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/MeshReductionInterface \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/MeshReductionInterface/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AssetTools \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Developer/AssetTools/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/KismetCompiler \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/KismetCompiler/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/GameplayTasks \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/GameplayTasks/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/GameplayTasks/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AIModule \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AIModule/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/AIModule/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Kismet \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/Kismet/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/Kismet/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/ClothingSystemRuntimeInterface \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/ClothingSystemRuntimeInterface/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/UMGEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/UMGEditor/Classes \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/UMGEditor/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/Sequencer \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/Sequencer/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/SceneOutliner \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/SceneOutliner/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/CurveEditor \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Editor/CurveEditor/Public \
	Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/LostWorld \
	Source \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/JsonUtilities \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/Runtime/JsonUtilities/Public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PxShared/include \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PxShared/include/cudamanager \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PxShared/include/filebuf \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PxShared/include/foundation \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PxShared/include/pvd \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PxShared/include/task \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/cooking \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/common \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/extensions \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/geometry \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/clothing \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/nvparameterized \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/legacy \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/PhysX3 \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/common/include \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/common/include/autogen \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/framework/include \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/framework/include/autogen \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/shared/general/RenderDebug/public \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/shared/general/PairFilter/include \
	/var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom/Engine/Source/ThirdParty/PhysX3/APEX_1.4/shared/internal/include \

