# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /var/home/bazzite/Documents/Unreal Engine/dev-4.27.2
GAMEPROJECTFILE =/home/bazzite/UnrealEngine/Projects/LostWorld 4.27/LostWorld.uproject

TARGETS = \
	LostWorld-Linux-DebugGame  \
	LostWorld-Linux-Shipping  \
	LostWorld \
	LostWorldEditor-Linux-DebugGame  \
	LostWorldEditor-Linux-Shipping  \
	LostWorldEditor \
	UE4Client-Linux-DebugGame  \
	UE4Client-Linux-Shipping  \
	UE4Client \
	UE4Editor-Linux-DebugGame  \
	UE4Editor-Linux-Shipping  \
	UE4Editor \
	UE4Game-Linux-DebugGame  \
	UE4Game-Linux-Shipping  \
	UE4Game \
	UE4Server-Linux-DebugGame  \
	UE4Server-Linux-Shipping  \
	UE4Server\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


LostWorld-Linux-DebugGame:
	 $(PROJECTBUILD) LostWorld Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorld-Linux-Shipping:
	 $(PROJECTBUILD) LostWorld Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorld:
	 $(PROJECTBUILD) LostWorld Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor-Linux-DebugGame:
	 $(PROJECTBUILD) LostWorldEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor-Linux-Shipping:
	 $(PROJECTBUILD) LostWorldEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor:
	 $(PROJECTBUILD) LostWorldEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-DebugGame:
	 $(BUILD) UE4Client Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client-Linux-Shipping:
	 $(BUILD) UE4Client Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Client:
	 $(BUILD) UE4Client Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-DebugGame:
	 $(BUILD) UE4Editor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor-Linux-Shipping:
	 $(BUILD) UE4Editor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Editor:
	 $(BUILD) UE4Editor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-DebugGame:
	 $(BUILD) UE4Game Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game-Linux-Shipping:
	 $(BUILD) UE4Game Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Game:
	 $(BUILD) UE4Game Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-DebugGame:
	 $(BUILD) UE4Server Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server-Linux-Shipping:
	 $(BUILD) UE4Server Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UE4Server:
	 $(BUILD) UE4Server Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
