# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /var/home/valerie/Documents/Programs/UnrealEngine_4.27_Custom
GAMEPROJECTFILE =/home/valerie/Documents/Projects/LostWorld/LostWorld.uproject

TARGETS = \
	LostWorld-Linux-Debug  \
	LostWorld-Linux-DebugGame  \
	LostWorld-Linux-Shipping  \
	LostWorld-Linux-Test  \
	LostWorld \
	LostWorldEditor-Linux-Debug  \
	LostWorldEditor-Linux-DebugGame  \
	LostWorldEditor-Linux-Shipping  \
	LostWorldEditor-Linux-Test  \
	LostWorldEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/RunMono.sh" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool.exe"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass

StandardSet: RequiredTools UnrealFrontend UE4Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UE4Editor-Linux-Debug


LostWorld-Linux-Debug:
	 $(PROJECTBUILD) LostWorld Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorld-Linux-DebugGame:
	 $(PROJECTBUILD) LostWorld Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorld-Linux-Shipping:
	 $(PROJECTBUILD) LostWorld Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorld-Linux-Test:
	 $(PROJECTBUILD) LostWorld Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorld:
	 $(PROJECTBUILD) LostWorld Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor-Linux-Debug:
	 $(PROJECTBUILD) LostWorldEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor-Linux-DebugGame:
	 $(PROJECTBUILD) LostWorldEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor-Linux-Shipping:
	 $(PROJECTBUILD) LostWorldEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor-Linux-Test:
	 $(PROJECTBUILD) LostWorldEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

LostWorldEditor:
	 $(PROJECTBUILD) LostWorldEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
